services:
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: test_job_production
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
volumes:
  db_data:
      